// Auto-generated by scripts/generate-icons-index-components.js
import { ReactComponent as ActivityArrows0 } from './activity-arrows.svg';
import { ReactComponent as Analytics1 } from './analytics.svg';
import { ReactComponent as BasicProblem2 } from './basic-problem.svg';
import { ReactComponent as BrowseAll3 } from './Browse all.svg';
import { ReactComponent as Cake4 } from './cake.svg';
import { ReactComponent as Cake5 } from './cake (1).svg';
import { ReactComponent as Classifieds6 } from './classifieds.svg';
import { ReactComponent as Clothings7 } from './clothings.svg';
import { ReactComponent as Comment12 } from './comment.svg';
import { ReactComponent as Communication5 } from './communication.svg';
import { ReactComponent as DetailedProblem6 } from './detailed-problem.svg';
import { ReactComponent as Entertainment8 } from './entertainment.svg';
import { ReactComponent as Event7 } from './event.svg';
import { ReactComponent as FacebookPage8 } from './facebook-page.svg';
import { ReactComponent as Family11 } from './family.svg';
import { ReactComponent as Feeds9 } from './feeds.svg';
import { ReactComponent as Friends10 } from './friends.svg';
import { ReactComponent as Home13 } from './home.svg';
import { ReactComponent as Image14 } from './image.svg';
import { ReactComponent as Logo15 } from './logo.svg';
import { ReactComponent as Lightmode16 } from './lightmode.svg';
import { ReactComponent as MapLocation17 } from './map-location_12519920.svg';

import { ReactComponent as Marketplace217 } from './marketplace (2).svg';
import { ReactComponent as Marketplace2 } from './marketplace2.svg';
import { ReactComponent as MarketplaceAccess18 } from './Marketplace access.svg';
import { ReactComponent as Memories18 } from './memories.svg';
import { ReactComponent as MessangerKids19 } from './messanger kids.svg';
import { ReactComponent as Messenger596877120 } from './messenger_5968771.svg';
import { ReactComponent as Messenger596877121 } from './messenger_596877.svg';
import { ReactComponent as Meta21 } from './meta.svg';
import { ReactComponent as NightMode22 } from './night-mode.svg';
import { ReactComponent as Notification22 } from './Notification.svg';
import { ReactComponent as Product22 } from './product.svg';
import { ReactComponent as Post25 } from './post.svg';
import { ReactComponent as Properties27 } from './properties.svg';

import { ReactComponent as Saved23 } from './saved.svg';
import { ReactComponent as Search24 } from './search (1).svg';
import { ReactComponent as Selling28 } from './selling.svg';
import { ReactComponent as Share27 } from './share.svg';
import { ReactComponent as Story26 } from './story.svg';
import { ReactComponent as Social1367034024 } from './social_13670340.svg';
import { ReactComponent as Social136g7034025 } from './social_136g70340.svg';
import { ReactComponent as Buy1098286430 } from './buy_10982864.svg';
import { ReactComponent as Inbox31 } from './inbox.svg';
import { ReactComponent as Laptop1823555832 } from './laptop_18235558.svg';
import { ReactComponent as Vehicels33 } from './vehicels.svg';


const icons = {
  "activity-arrows": ActivityArrows0,
  "analytics": Analytics1,
  "basic-problem": BasicProblem2,
  "browse-all": BrowseAll3,
  "cake": Cake4,
  "cake (1)": Cake5,
  "classifieds": Classifieds6,
  "clothings": Clothings7,
  "comment": Comment12,
  "communication": Communication5,
  "detailed-problem": DetailedProblem6,
  "entertainment": Entertainment8,
  "event": Event7,
  "facebook-page": FacebookPage8,
  "family": Family11,
  "feeds": Feeds9,
  "friends": Friends10,

  "home": Home13,
  "image": Image14,
  "logo": Logo15,
  "lightmode": Lightmode16,
  "map-location": MapLocation17,

  "marketplace (2)": Marketplace217,
  "marketplace2": Marketplace2,
  "marketplace-access": MarketplaceAccess18,
  "memories": Memories18,
  "messanger kids": MessangerKids19,
  "messenger_5968771": Messenger596877120,
  "messenger_596877": Messenger596877121,
  "meta": Meta21,
  "night-mode": NightMode22,
  "notification": Notification22,
  "product": Product22,
  "post": Post25,
  "properties": Properties27,

  "saved": Saved23,
  "search (1)": Search24,
  "selling": Selling28,
  "share": Share27,
  "story": Story26,
  "social_13670340": Social1367034024,
  "social_136g70340": Social136g7034025,
  "buy_10982864": Buy1098286430,
  "inbox": Inbox31,
  "laptop_18235558": Laptop1823555832,
  "vehicels": Vehicels33,

};

export default icons;
